courses/urls.py
from django.conf.urls import patterns, url

from courses import views

urlpatterns = patterns('',
    url(r'^$', views.courses, name='courses'),
    url(r'^(?P<course_id>\d+)/$', views.course_detail, name='course_detail'),
    url(r'^add_course/(?P<profile_id>\d+)/(?P<term_id>\d+)/$', views.add_course, name='add_course'),
    url(r'^add_course_action/(?P<profile_id>\d+)/(?P<term_id>\d+)/$', views.add_course_action, name='add_course_action'),
    url(r'^remove_course/(?P<profile_id>\d+)/(?P<term_id>\d+)/$', views.remove_course, name='remove_course'),
    url(r'^remove_course_action/(?P<profile_id>\d+)/(?P<term_id>\d+)/$', views.remove_course_action, name='remove_course_action'),
    url(r'^s/$', views.search_course, name='search_course')
)

magellan2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from users.models import Course

urlpatterns = patterns('',

    # URL for the index page:
    url(r'^$', 'users.views.index', name='index'),
    url(r'^home$', 'users.views.home', name='home'),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    # Include URLs from all apps
    url(r'^users/', include('users.urls')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^courses/', include('courses.urls', namespace='courses')),

    # Include URLs from all apps
    url(r'^admin/', include(admin.site.urls)),

)

profiles/urls.py
from django.conf.urls import patterns, url

from profiles import views

urlpatterns = patterns('',
    url(r'^$', views.profiles, name='profiles'),
    url(r'^requirements', views.requirements, name='requirements'),
    url(r'^(?P<profile_id>\d+)/$', views.profile_detail, name='profile_detail'),
    url(r'^view_profiles$', views.view_profiles, name='view_profiles'),
    url(r'^view_current_profile/(?P<profile_id>\d+)/$', views.view_current_profile, name='view_current_profile'),
    url(r'^create_profile$', views.create_profile, name='create_profile'),
    url(r'^delete_profile/(?P<profile_id>\d+)/$', views.delete_profile, name='delete_profile'),
    url(r'^create_term/(?P<profile_id>\d+)/$', views.create_term, name='create_term')
)

users/urls.py
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    url(r'^edit', views.edit_user_info, name='edit_user_info')
)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import Course, Student


class Profile(models.Model):
    student = models.ForeignKey(Student)
    profile_name = models.CharField(max_length=200)
    #staging_list = models.ManyToManyField(Course, related_name='profile_staging_list' ,through='StagingList', through_fields=('profile', 'course'), blank=True)
    #locked_in_list = models.ManyToManyField(Course, related_name='profile_locked_in_list', through='LockedInList', through_fields=('profile', 'course'), blank=True)

    def __unicode__(self):
        return self.profile_name

class Term(models.Model):
    profile = models.ForeignKey(Profile)
    year = models.DecimalField(max_digits=4, decimal_places=0, default=2010)
    season=models.CharField(max_length=10,default='FALL')
    courses = models.ManyToManyField(Course)

    def __unicode__(self):
        return self.profile.profile_name + " "+ str(self.year)+ " " + self.season


class StagingList(models.Model):
  #  class Meta:
   #     auto_created = True
    #term = models.ForeignKey(Term)
    course = models.ForeignKey(Course)
    selected = models.BooleanField(default=False)
    #term = models.IntegerField(default = 0)

    def __unicode__(self):
        return self.term.profile.profile_name+ " "+ str(self.term.year)+ " " + self.term.season + " "+ self.course.course_code + " " + self.selected



class LockedInList(models.Model):
    #class Meta:
     #   auto_created = True
    term = models.ForeignKey(Term)
    course = models.ForeignKey(Course)
    section = models.CharField(max_length=6)
    def __unicode__(self):
        return  self.term.profile.profile_name+ " "+ str(self.term.year)+ " " + self.term.season + " " + self.course.course_code + " " + self.section

profiles/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf

from users.models import Course, Student
from profiles.models import*



# Create your views here.



@login_required
def requirements(request):
    return render(request, 'requirements.html')


@login_required
def profiles(request):
    current_student = request.user.student
    list_of_profiles = current_student.profile_set.all()
    context = {'list_of_profiles': list_of_profiles}
    return render(request, 'profiles.html', context)



@login_required
def profile_detail(request, profile_id):
    profile = ()
    return render(request, 'profile_detail.html', {'profile': profile})


@login_required
def view_profiles(request):
    current_student = request.user.student
    list_of_profiles = current_student.profile_set.all()
    context = {'list_of_profiles': list_of_profiles}
    return render(request, 'profiles/view_profiles.html', context)

@login_required
def view_current_profile(request, profile_id):
    # when matching with id, there should only be one match
    # the AUTH_USER_PROFILE is set to the Student model
    current_student = request.user.student
    try:
        current_profile = current_student.profile_set.get(pk=profile_id)
    except Profile.DoesNotExist:
        raise Http404("Profile ID does not exist for this student")

    # Create AU totals
    # TODO: separate into more general function
    # compute total for MAT (NEED TO DO REST)
    math_credits = 0
    ns_credits = 0    # ERROR: this makes the display show up as 0?
    es_credits = 0
    ed_credits = 0
    cs_credits = 0

    list_of_term = current_profile.term_set.all()
    staging_list ={}

    try:
        for term in list_of_term:
            staging_list.append(term.staginglist_set.all())
            for entry in staging_list:
                 # the type conversion is needed, otherwise this return an annoying python Decimal object
                math_credits += float(entry.course.course_math)
                ns_credits += float(entry.course.course_ns)
                es_credits += float(entry.course.course_es)
                ed_credits += float(entry.course.course_ed)
                cs_credits += float(entry.course.course_cs)
    except:
        cs_credits=cs_credits
    mns_credits = math_credits + ns_credits
    eec_credits = es_credits + ed_credits

    # may want to get these from a table later
    ceabReq = {
        'AU' : 1950,
        'MAT' : 214.5,
        'NS' : 200.0,
        'MNC' : 462,
        'ES' : 247.5,
        'ED' : 247.5,
        'EEC' : 990,
        'CS' : 240
    }
    ceab = {
        'AU' : 1884.7,
        'MAT' : math_credits,
        'NS' : ns_credits,
        'MNC' : mns_credits,
        'ES' : es_credits,
        'ED' : ed_credits,
        'EEC' : eec_credits,
        'CS' : cs_credits
    }
    context = {'list_of_term': list_of_term, 'staging_list':staging_list,'profile_id': profile_id, 'ceab': ceab,
               'ceabReq': ceabReq}
    return render(request, 'profiles/view_current_profile.html', context)

@login_required
def create_profile(request):
    current_student = request.user.student
    # add the profile
    new_profile = Profile()
    new_profile.profile_name = 'Another new profile'
    new_profile.student = current_student
    new_profile.save()
    # display the updated list
    #return HttpResponseRedirect(reverse('profiles:view_profiles'))
    return HttpResponseRedirect(reverse('profiles:profiles'))

@login_required
def delete_profile(request, profile_id):
    current_student = request.user.student
    # delete the profile
    profile_to_delete = current_student.profile_set.get(pk=profile_id)
    profile_to_delete.delete()
    # display the updated list
    #return HttpResponseRedirect(reverse('profiles:view_profiles'))
    return HttpResponseRedirect(reverse('profiles:profiles'))

@login_required
def create_term(request,profile_id):
    current_student = request.user.student
    try:
        current_profile = current_student.profile_set.get(pk=profile_id)
    except Profile.DoesNotExist:
        raise Http404("Profile ID does not exist for this student")
    new_term = Term()
    new_term.year = 2010
    new_term.season ='FALL'
    new_term.profile = current_profile
    new_term.save()
    return HttpResponseRedirect(reverse('profiles:view_current_profile',args=(profile_id,)))

profiles/templates/profiles/view_current_profile.html
{% extends "private_base.html" %}

{% load staticfiles %}

{% block content %}
<section id="course-view" class="" name="course-view">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div role="tabpanel">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#r-view" aria-controls="r-view" role="tab" data-toggle="tab">Requirments View</a>
                        </li>
                        <li role="presentation">
                            <a href="#t-view" aria-controls="t-view" role="tab" data-toggle="tab">Timeline View</a>
                        </li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="r-view">Requirement View</div>
                        <div role="tabpanel" class="tab-pane" id="t-view">Timeline View</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section id="course-search" class="section-top-margin" name="course-search">
    <div class="row">
        <div class="col-sm-3 search-column">
            <h4> Courses (<span id="total_courses">250</span>)</h4>

            <div class="search-row">
                <input type="text" id="searchbox" placeholder="Search...">
                <span class="glyphicon glyphicon-search search-icon"></span>
            </div>

            <div class="term filter-switch">
                <div class="btn-group" data-toggle="buttons">
                    <label class="btn btn-success active">
                        <input type="radio" name="options" id="fall" autocomplete="off" checked> Fall
                    </label>
                    <label class="btn btn-success">
                        <input type="radio" name="options" id="winter" autocomplete="off"> Winter
                    </label>

                </div>
            </div>

            <div class="kernel filter-switch">
                <div class="btn-group" data-toggle="buttons">
                    <label class="btn btn-success active">
                        <input type="radio" name="options" id="k" autocomplete="off" checked> Kernel
                    </label>
                    <label class="btn btn-success">
                        <input type="radio" name="options" id="nk" autocomplete="off"> Non-Kernel
                    </label>

                </div>
            </div>

            <div class="criteria" id="area_criteria">
                <h4>Category</h4>

                <div class="btn-group-vertical category-btn" data-toggle="buttons">
                    <label class="btn btn-default active">
                        <input type="checkbox" name="options" class="btn" id="option0" autocomplete="off" checked> ALL

                    </label>
                    <label class="btn btn-default" data-container="body" data-toggle="popover" data-placement="right"
                           data-content="Photonics & Semiconductor Physics">
                        <input type="checkbox" name="options" id="option1" autocomplete="off" value="1"> Area 1
                    </label>
                    <label class="btn btn-default" data-container="body" data-toggle="popover" data-placement="right"
                           data-content="Electromagnetics & Energy Systems">
                        <input type="checkbox" name="options" id="option2" autocomplete="off"> Area 2
                    </label>
                    <label class="btn btn-default" data-container="body" data-toggle="popover" data-placement="right"
                           data-content="Analog & Digital Electronics">
                        <input type="checkbox" name="options" id="option3" autocomplete="off"> Area 3
                    </label>
                    <label class="btn btn-default" data-container="body" data-toggle="popover" data-placement="right"
                           data-content="Control, Communications & Signal Processing">
                        <input type="checkbox" name="options" id="option4" autocomplete="off"> Area 4
                    </label>
                    <label class="btn btn-default" data-container="body" data-toggle="popover" data-placement="right"
                           data-content="Computer Hardware & Computer Networks">
                        <input type="checkbox" name="options" id="option5" autocomplete="off"> Area 5
                    </label>
                    <label class="btn btn-default" data-container="body" data-toggle="popover" data-placement="right"
                           data-content="Software">
                        <input type="checkbox" name="options" id="option6" autocomplete="off"> Area 6
                    </label>
                    <label class="btn btn-default">
                        <input type="checkbox" name="options" id="option8" autocomplete="off"> Math/Science
                    </label>
                    <label class="btn btn-default">
                        <input type="checkbox" name="options" id="option7" autocomplete="off"> Mandatory
                    </label>
                    <label class="btn btn-default">
                        <input type="checkbox" name="options" id="option9" autocomplete="off"> HSS
                    </label>
                    <label class="btn btn-default">
                        <input type="checkbox" name="options" id="option10" autocomplete="off"> CS
                    </label>
                    <label class="btn btn-default">
                        <input type="checkbox" name="options" id="option11" autocomplete="off"> FREE ELECTIVE
                    </label>
                </div>
            </div>
        </div>

        <div class="courses-content col-sm-9" id="profile-courses">
             <script id="course-template" type="text/html">
                <div class="col-sm-4 course-box">
                    <div class="course-details">
                        <h4><%= name %></h4>
                        <h5><%= area %></h5>
                    </div>
                </div>
            </script>
        </div>

    </div>
</section>

<!-- ========== COURSE SECTION ========== -->
<section id="requirements" class="jumbotron requirements-section" name="requirements">


    <a href="{% url 'profiles:create_term' profile_id %}" class="btn btn-primary btn-xs pull-right"><b>+</b> Create a
        new semester</a>
    {% if list_of_term %}
    <ul>
        {% for term in list_of_term %}
        <li>
            {% if term.courses.all %}

            <ul>
                {% for course in term.courses.all %}
                <li>
                    <a href="/courses/{{ course.id }}/">{{ course_code }}</a>
                    <input type="radio" name="course_choice" id="course_choice{{ forloop.counter }}"
                           value="{{ course.id }}"/>
                    <a href="/courses/{{ course.id }}/">{{ course.course_code }} </a>

                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>You have not signed up for any courses yet.</p>
            {% endif %}


        <li>
            <a class="" href="{% url 'courses:add_course' profile_id term.id %}">Add courses</a>
        </li>
        <li>
            <a class="" href="{% url 'courses:remove_course' profile_id term.id %}">Remove course</a>
        </li>
        <li>
            <a class="" href="{% url 'profiles:profiles' %}">Return to profiles list</a>
        </li>

        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>You have not create a semester</p>
    {% endif %}


    </div>

</section>

<section id="stat" class="stat-section ">
    <div class="container">
        <h2 class=""> CEAB Requirements </h2>

        <div class="row radial-top">
            <div id="AU" class=" col-md-3 col-sm-6 relative-pos">
                <button tabindex="0"
                        class="btn btn-default ceab-detail"
                        id="popover"
                        data-placement="top"
                        type="button"
                        data-toggle="popover" data-container="body" title="Title" data-content="Content">Click to View
                    Details
                </button>
            </div>
            <div id="MAT" class=" col-md-3 col-sm-6 relative-pos"></div>
            <div id="NS" class=" col-md-3 col-sm-6 relative-pos"></div>
            <div id="MNC" class="col-md-3 col-sm-6 relative-pos"></div>
        </div>
        <div class="row radial-bottom">
            <div id="ES" class="col-md-3 col-sm-6 relative-pos"></div>
            <div id="ED" class="col-md-3 col-sm-6 relative-pos"></div>
            <div id="EEC" class="col-md-3 col-sm-6 relative-pos"></div>
            <div id="CS" class="col-md-3 col-sm-6 relative-pos"></div>
        </div>

    </div>
</section>

<script type="text/javascript" src="{% static  'js/vendor/filter.min.js' %}"></script>

<script type="text/javascript">
      var courses = [
            {
                "name": "Course 1",
                "area": ["1"]
            },
            {
                "name": "Course 2",
                "area": ["2"]
            },
            {
                "name": "Course 3",
                "area": ["3"]
            },
            {
                "name": "Course 4",
                "area": ["4"]
            }
        ];
</script>

<script type="text/javascript">

    $(document).ready(function(){

        //NOTE: To append in different container
        var appendToContainer = function(htmlele, record){
            console.log(record)
        };

        var FJS = FilterJS(courses, '#profile-courses', {
            template: '#course-template',
            search: {ele: '#searchbox'},

            callbacks: {
                afterFilter: function(result){
                    $('#total_courses').text(result.length);
                }
            }
            //appendToContainer: appendToContainer
        });

        FJS.addCriteria({field: 'area', ele: '#area_criteria input:checkbox'});


        window.FJS = FJS;

  });

</script>


<script type="text/javascript">
        $(document).ready(function() {
             $('[data-toggle="tooltip"]').tooltip();
             $('[data-toggle="popover"]').popover({ trigger: "hover" });
        });

        //http://www.bootstrap-switch.org/

</script>

{% endblock %}