magellan2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from users.models import Course

urlpatterns = patterns('',

    # URL for the index page:
    url(r'^$', 'users.views.index', name='index'),
    url(r'^home$', 'users.views.home', name='home'),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    # Include URLs from all apps
    url(r'^users/', include('users.urls')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^courses/', include('courses.urls', namespace='courses')),

    # Include URLs from all apps
    url(r'^admin/', include(admin.site.urls)),

)

profiles/urls.py
from django.conf.urls import patterns, url

from profiles import views

urlpatterns = patterns('',
    url(r'^$', views.profiles, name='profiles'),
    url(r'^requirements', views.requirements, name='requirements'),
    url(r'^(?P<profile_id>\d+)/$', views.profile_detail, name='profile_detail'),
    url(r'^view_profiles$', views.view_profiles, name='view_profiles'),
    url(r'^view_current_profile/(?P<profile_id>\d+)/$', views.view_current_profile, name='view_current_profile'),
    url(r'^create_profile$', views.create_profile, name='create_profile'),
    url(r'^delete_profile/(?P<profile_id>\d+)/$', views.delete_profile, name='delete_profile'),
    url(r'^create_term/(?P<profile_id>\d+)/$', views.create_term, name='create_term')
)

users/urls.py
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    url(r'^edit', views.edit_user_info, name='edit_user_info')
)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import Course, Student


class Profile(models.Model):
    student = models.ForeignKey(Student)
    profile_name = models.CharField(max_length=200)
    #staging_list = models.ManyToManyField(Course, related_name='profile_staging_list' ,through='StagingList', through_fields=('profile', 'course'), blank=True)
    #locked_in_list = models.ManyToManyField(Course, related_name='profile_locked_in_list', through='LockedInList', through_fields=('profile', 'course'), blank=True)

    def __unicode__(self):
        return self.profile_name

class Term(models.Model):
    profile = models.ForeignKey(Profile)
    year = models.DecimalField(max_digits=4, decimal_places=0, default=2010)
    season=models.CharField(max_length=10,default='FALL')
    courses = models.ManyToManyField(Course)

    def __unicode__(self):
        return self.profile.profile_name + " "+ str(self.year)+ " " + self.season


class StagingList(models.Model):
  #  class Meta:
   #     auto_created = True
    #term = models.ForeignKey(Term)
    course = models.ForeignKey(Course)
    selected = models.BooleanField(default=False)
    #term = models.IntegerField(default = 0)

    def __unicode__(self):
        return self.term.profile.profile_name+ " "+ str(self.term.year)+ " " + self.term.season + " "+ self.course.course_code + " " + self.selected



class LockedInList(models.Model):
    #class Meta:
     #   auto_created = True
    term = models.ForeignKey(Term)
    course = models.ForeignKey(Course)
    section = models.CharField(max_length=6)
    def __unicode__(self):
        return  self.term.profile.profile_name+ " "+ str(self.term.year)+ " " + self.term.season + " " + self.course.course_code + " " + self.section

profiles/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf

from users.models import Course, Student
from profiles.models import*



# Create your views here.



@login_required
def requirements(request):
    return render(request, 'requirements.html')


@login_required
def profiles(request):
    current_student = request.user.student
    list_of_profiles = current_student.profile_set.all()
    context = {'list_of_profiles': list_of_profiles}
    return render(request, 'profiles.html', context)



@login_required
def profile_detail(request, profile_id):
    profile = ()
    return render(request, 'profile_detail.html', {'profile': profile})


@login_required
def view_profiles(request):
    current_student = request.user.student
    list_of_profiles = current_student.profile_set.all()
    context = {'list_of_profiles': list_of_profiles}
    return render(request, 'profiles/view_profiles.html', context)

@login_required
def view_current_profile(request, profile_id):
    # when matching with id, there should only be one match
    # the AUTH_USER_PROFILE is set to the Student model
    current_student = request.user.student
    try:
        current_profile = current_student.profile_set.get(pk=profile_id)
    except Profile.DoesNotExist:
        raise Http404("Profile ID does not exist for this student")

    # Create AU totals
    # TODO: separate into more general function
    # compute total for MAT (NEED TO DO REST)
    math_credits = 0
    ns_credits = 0    # ERROR: this makes the display show up as 0?
    es_credits = 0
    ed_credits = 0
    cs_credits = 0

    list_of_term = current_profile.term_set.all()
    staging_list ={}

    try:
        for term in list_of_term:
            staging_list.append(term.staginglist_set.all())
            for entry in staging_list:
                 # the type conversion is needed, otherwise this return an annoying python Decimal object
                math_credits += float(entry.course.course_math)
                ns_credits += float(entry.course.course_ns)
                es_credits += float(entry.course.course_es)
                ed_credits += float(entry.course.course_ed)
                cs_credits += float(entry.course.course_cs)
    except:
        cs_credits=cs_credits
    mns_credits = math_credits + ns_credits
    eec_credits = es_credits + ed_credits

    # may want to get these from a table later
    ceabReq = {
        'AU' : 1950,
        'MAT' : 214.5,
        'NS' : 200.0,
        'MNC' : 462,
        'ES' : 247.5,
        'ED' : 247.5,
        'EEC' : 990,
        'CS' : 240
    }
    ceab = {
        'AU' : 1884.7,
        'MAT' : math_credits,
        'NS' : ns_credits,
        'MNC' : mns_credits,
        'ES' : es_credits,
        'ED' : ed_credits,
        'EEC' : eec_credits,
        'CS' : cs_credits
    }
    context = {'list_of_term': list_of_term, 'staging_list':staging_list,'profile_id': profile_id, 'ceab': ceab,
               'ceabReq': ceabReq}
    return render(request, 'profiles/view_current_profile.html', context)

@login_required
def create_profile(request):
    current_student = request.user.student
    # add the profile
    new_profile = Profile()
    new_profile.profile_name = 'Another new profile'
    new_profile.student = current_student
    new_profile.save()
    # display the updated list
    #return HttpResponseRedirect(reverse('profiles:view_profiles'))
    return HttpResponseRedirect(reverse('profiles:profiles'))

@login_required
def delete_profile(request, profile_id):
    current_student = request.user.student
    # delete the profile
    profile_to_delete = current_student.profile_set.get(pk=profile_id)
    profile_to_delete.delete()
    # display the updated list
    #return HttpResponseRedirect(reverse('profiles:view_profiles'))
    return HttpResponseRedirect(reverse('profiles:profiles'))

@login_required
def create_term(request,profile_id):
    current_student = request.user.student
    try:
        current_profile = current_student.profile_set.get(pk=profile_id)
    except Profile.DoesNotExist:
        raise Http404("Profile ID does not exist for this student")
    new_term = Term()
    new_term.year = 2010
    new_term.season ='FALL'
    new_term.profile = current_profile
    new_term.save()
    return HttpResponseRedirect(reverse('profiles:view_current_profile',args=(profile_id,)))

templates/ajax_search.html
          {% for course in courses %}
          <tr>
            <td>{{ course.course_code }}</td>
            <td>{{ course.course_title }}</td>
            <td class="text-right"><button class="btn btn-primary btn-xs" name="man_id" value="{{ result.course_code }}">Add</button></td>
          </tr>
          {% endfor %}




<!-- {% if courses.count > 0 %}

{% for course in courses %}
	<li><a href="/courses/{{ course.id }}">{{course.course_title}}</a></li>
{% endfor %}

{% else %}

<li>None to show!</li>

{% endif %} -->

templates/course_detail.html
{% extends "private_base.html" %}

{% block content %}

    <!-- Load c3.css -->
    <link href="/static/css/c3.min.css" rel="stylesheet" type="text/css">

    <!-- Load d3.js and c3.js -->
    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="/static/js/c3.min.js"></script>

    <!-- ========== COURSE DEATIL SECTION ========== -->
    <section id="courses" class="jumbotron courses-section" name="courses">
            <div class="container">
                <h2 class="text-center"> Course Detail </h2>

                <h2>{{ course.course_code }}</h2>
                <h3>{{ course.course_title }}</h3>
                <h5>{{ course.course_description }}</h5>
                <h4>Prerequisites: {{ course.course_prerequisites }}</h4>
                <h4>Corequisites: {{ course.course_corequisites }}</h4>
                <h4>Exclusions: {{ course.course_exclusions }}</h4>
                <h4>Credit Weight: {{ course.course_credit_weight }}</h4>
                <h4>Credit Area: {{ course.course_area }}</h4>
                <h4>Credit CEAB AU: </h4>

                <div id="chart"></div>
                <script>
                    var chart = c3.generate({
                        data: {
                            columns: [
                                ['MATH', {{course.course_math}}],
                                ['NS', {{course.course_ns}}],
                                ['CS', {{course.course_cs}}],
                                ['ES', {{course.course_es}}],
                                ['ED', {{course.course_ed}}]

                            ],
                            type: 'pie'
                        },
                        pie: {
                            label: {
                                format: function (value, ratio, id) {
                                    return d3.format('')(value);
                                }
                            }
                        }
                    });

                </script>

            </div>
    </section>

{% endblock %}

templates/edit_user_info.html
{% extends "private_base.html" %}

{% block content %}
<section id="edit-user-info-section" class="" name="edit-user-info">
    <div class="container">
         <h1 class="">Edit Personal Information</h1>

        <div class="row">
            <!-- left column -->
            <div class="col-md-3">
                <div class="text-center">
                    <img src="//placehold.it/100" class="avatar img-circle" alt="avatar">
                     <h5 class="">Upload a different photo...</h5>

                    <input class="form-control" type="file">
                </div>
            </div>
            <!-- edit form column -->
            <div class="col-md-9 personal-info">
                <div style="display: none;" class="alert alert-info alert-dismissable">
                    <a class="panel-close close" data-dismiss="alert">×</a>  <i class="fa fa-coffee"></i>
                        This is an <strong class="">.alert</strong>.
                        Use this to show important messages to the user.
                </div>

                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label class="col-lg-3 control-label">First name:</label>
                        <div class="col-lg-8">
                            <input class="form-control" value="Jane" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Last name:</label>
                        <div class="col-lg-8">
                            <input class="form-control" value="Bishop" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Company:</label>
                        <div class="col-lg-8">
                            <input class="form-control" value="" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Email:</label>
                        <div class="col-lg-8">
                            <input class="form-control" value="janesemail@gmail.com" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Time Zone:</label>
                        <div class="col-lg-8">
                            <div class="ui-select">
                                <select id="user_time_zone" class="form-control">
                                    <option class="" value="Hawaii">(GMT-10:00) Hawaii</option>
                                    <option class="" value="Alaska">(GMT-09:00) Alaska</option>
                                    <option class="" value="Pacific Time (US &amp; Canada)">(GMT-08:00) Pacific Time (US &amp; Canada)</option>
                                    <option class="" value="Arizona">(GMT-07:00) Arizona</option>
                                    <option class="" value="Mountain Time (US &amp; Canada)">(GMT-07:00) Mountain Time (US &amp; Canada)</option>
                                    <option class="" value="Central Time (US &amp; Canada)" selected="selected">(GMT-06:00) Central Time (US &amp; Canada)</option>
                                    <option class="" value="Eastern Time (US &amp; Canada)">(GMT-05:00) Eastern Time (US &amp; Canada)</option>
                                    <option class="" value="Indiana (East)">(GMT-05:00) Indiana (East)</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Username:</label>
                        <div class="col-md-8">
                            <input class="form-control" value="janeuser" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Password:</label>
                        <div class="col-md-8">
                            <input class="form-control" value="11111122333" type="password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Confirm password:</label>
                        <div class="col-md-8">
                            <input class="form-control" value="11111122333" type="password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label"></label>
                        <div class="col-md-8">
                            <input class="btn btn-primary" value="Save Changes" type="button"> <span class=""></span>

                            <input class="btn btn-default" value="Cancel" type="reset">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>


{% endblock %}

templates/login.html
{% extends "public_base.html" %}

{% block content %}

<nav class=" navbar-custom  top-nav-collapse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand page-scroll" href="{% url 'index' %}">
                <i class="fa fa-play-circle"></i> Magellan <span class="blue-text">II</span>
            </a>
        </div>
    </div>
</nav>

<section id="login-section">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                        Sorry, that's not a valid username or password
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="well login-box">
                    <form action="{% url 'django.contrib.auth.views.login' %}" method="post">{% csrf_token %}
                        <legend>Login</legend>
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input value='' id="username" name="username" placeholder="" type="text" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input id="password" name="password" value='' placeholder="" type="password" class="form-control" />
                        </div>
                        <div class="form-group text-center">
                            <a class="btn btn-danger btn-cancel-action" href="{% url 'index' %}">Cancel</a>
                            <input type="submit" class="btn btn-success btn-login-submit" value="Login" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

templates/private_base.html
<!DOCTYPE html>
<html class="no-js" lang="" xmlns="http://www.w3.org/1999/html">
<head lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Magellan II</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="assets/ico/favicon.png">

    <!-- Place favicon.ico in the root directory -->

    <link rel="stylesheet" href="/static/css/normalize.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/shared.css">
    <link rel="stylesheet" href="/static/css/home.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <link rel="stylesheet" href="/static/css/d3_radial_progress.css">
    <link rel="stylesheet" href="/static/css/custom_radial_progress.css">
    <link rel="stylesheet" href="/static/css/course.css" />
    <link rel="stylesheet" href="/static/css/edit_profile.css" />

    <!-- Custom Fonts -->
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <script src="/static/js/vendor/modernizr-2.8.3.min.js"></script>
    <script src="/static/js/vendor/jquery-1.11.2.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-custom navbar-fixed-top top-nav-collapse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">
                    <i class="fa fa-play-circle"></i>  Magellan <span class="blue-text">II</span>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="" href="{% url 'profiles:profiles'%}">Profiles</a>
                    </li>
                    <li>
                        <a class="" href="{% url 'courses:courses'%}">Courses</a>
                    </li>
                    <!--<li>-->
                        <!--<a class="" href="{% url 'profiles:view_current_profile' 1%}">Enrolled Courses</a>-->
                    <!--</li>-->
                    <li>
                        <a class="" href="{% url 'profiles:requirements'%}">Requirements</a>
                    </li>
                    <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account <b class="caret"></b></a>
                            <ul class="dropdown-menu account-menu">
                                <li><a href="{% url 'edit_user_info'%}">Edit Profile</a></li>
                                <li><a href="#">Settings</a></li>
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                            </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <div class="container base-container">

    {% block content %}


    {% endblock %}

    </div> <!-- /container -->

                <!-- ========== FOOTER ========== -->
    <hr>
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; 2015 ECE450. All rights reserved.</p>
        </div>
    </footer>

    <script src="/static/js/vendor/bootstrap.min.js"></script>
    <script src="/static/js/vendor/jquery.easing.min.js"></script>
    <script src="/static/js/home.js"></script>


</body>
</html>

templates/profiles.html
{% extends "private_base.html" %}

{% block content %}

<!-- ========== COURSE SECTION ========== -->
<section id="requirements" class="requirements-section" name="requirements">
    <div class="container">
        <h2 class=""> Profile </h2>

    </div>
    <div class="container">
        <div class="row col-md-10 col-md-offset-1 custyle">
            <table class="table table-striped custab">
                <thead>
                <a href="{% url 'profiles:create_profile' %}" class="btn btn-primary btn-xs pull-right"><b>+</b> Create a new profile</a>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Last modified date</th>
                    <th class="text-center">Action</th>
                </tr>
                </thead>

                {% for profile in list_of_profiles %}
                <tr>
                    <!-- TODO: NOT SURE WHICH VALUE TO USE <td>{{ forloop.counter }}</td> -->
                    <td>{{ profile.id }}</td>
                    <td>{{ profile.profile_name }}</td>
                    <td>2015-01-01 13:00</td>
                    <td class="text-center">
                        <a href="{% url 'profiles:view_current_profile' profile.id %}" class="btn btn-success btn-xs"> <span class="glyphicon glyphicon-eye-open"></span> View </a>
                        <a href="{% url 'profiles:delete_profile' profile.id %}" class="btn btn-danger btn-xs">  <span class="glyphicon glyphicon-remove"></span> Del </a>
                    </td>
                </tr>
                {% endfor %}
          

            </table>
        </div>
    </div>

</section>

{% endblock %}

templates/public_base.html
<!doctype html>
<html class="no-js" lang="" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Magellan II</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="assets/ico/favicon.png">

        <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="/static/css/normalize.css">
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/grayscale.css">
        <link rel="stylesheet" href="/static/css/shared.css">
        <link rel="stylesheet" href="/static/css/main.css">

        <!-- Custom Fonts -->
        <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

        <script src="/static/js/vendor/modernizr-2.8.3.min.js"></script>
    </head>
    <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->


        {% block content %}


        {% endblock %}


                <!-- ========== FOOTER ========== -->
        <footer>
            <div class="container text-center">
                <p>Copyright &copy; 2015 ECE450. All rights reserved.</p>
            </div>
        </footer>


        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
        <script src="/static/js/vendor/bootstrap.min.js"></script>
        <script src="/static/js/vendor/jquery.easing.min.js"></script>
        <script src="/static/js/vendor/grayscale.js"></script>
        <script src="/static/js/plugins.js"></script>
        <script src="/static/js/main.js"></script>


        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

templates/requirements.html
{% extends "private_base.html" %}

{% block content %}

    <!-- ========== COURSE SECTION ========== -->
    <section id="requirements" class="requirements-section" name="requirements">
            <div class="container">
                <h2 class=""> Requirements </h2>

            </div>
    </section>

{% endblock %}